################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../gecko_sdk_4.4.0/platform/emlib/src/em_burtc.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_cmu.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_core.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_emu.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_eusart.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_gpio.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_i2c.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_iadc.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_ldma.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_msc.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_prs.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_system.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_timer.c \
../gecko_sdk_4.4.0/platform/emlib/src/em_usart.c 

OBJS += \
./gecko_sdk_4.4.0/platform/emlib/src/em_burtc.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_core.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_emu.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_eusart.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_i2c.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_iadc.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_msc.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_prs.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_system.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_timer.o \
./gecko_sdk_4.4.0/platform/emlib/src/em_usart.o 

C_DEPS += \
./gecko_sdk_4.4.0/platform/emlib/src/em_burtc.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_core.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_emu.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_eusart.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_i2c.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_iadc.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_msc.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_prs.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_system.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_timer.d \
./gecko_sdk_4.4.0/platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.4.0/platform/emlib/src/em_burtc.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_burtc.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_cmu.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_cmu.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_core.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_core.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_emu.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_emu.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_eusart.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_eusart.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_eusart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_gpio.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_gpio.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_i2c.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_i2c.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_iadc.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_iadc.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_iadc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_ldma.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_ldma.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_msc.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_msc.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_prs.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_prs.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_prs.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_system.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_system.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_timer.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_timer.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.0/platform/emlib/src/em_usart.o: ../gecko_sdk_4.4.0/platform/emlib/src/em_usart.c gecko_sdk_4.4.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFM32PG23B310F512IM48=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\App" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\BSP" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\PLM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\config" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\autogen" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\Device\SiliconLabs\EFM32PG23\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\CMSIS\Core\Include" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\device_init\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\dmadrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\common\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emlib\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\peripheral\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\common\toolchain\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\system\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\service\sleeptimer\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\spidrv\inc" -I"C:\Users\ebt\Documents\Xavier\Firmware\Simplicity\POD_STIM\gecko_sdk_4.4.0\platform\emdrv\uartdrv\inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.0/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


